/**
 * Rechtstexte (Impressum / AGB / Datenschutz) — verbatim aus den alten HTML-
 * Dateien. Zeilen für den rich()-Builder: "## " h2, "### " h3, "- " Liste.
 */

export const IMPRESSUM_LINES: string[] = [
  '## Impressum',
  '### Angaben gemäss § 5 TMG',
  'Marco Burgmeijer',
  'RAI-Experte',
  'Sunnmatt 1',
  '8634 Hombrechtikon',
  'Schweiz',
  '### Kontakt',
  'Telefon: +41 76 457 44 82',
  'E-Mail: rai-experte@gmx.ch',
  '### Unternehmensidentifikationsnummer',
  'UID: CHE-294.549.553',
  '### Verantwortlich für den Inhalt',
  'Marco Burgmeijer',
  'Sunnmatt 1',
  '8634 Hombrechtikon',
  'Schweiz',
  '### Haftungsausschluss',
  'Die Inhalte dieser Webseite wurden mit grösstmöglicher Sorgfalt erstellt. Für die Richtigkeit, Vollständigkeit und Aktualität der Inhalte kann jedoch keine Gewähr übernommen werden. Als Dienstanbieter bin ich gemäss § 7 Abs.1 TMG für eigene Inhalte auf diesen Seiten nach den allgemeinen Gesetzen verantwortlich. Nach §§ 8 bis 10 TMG bin ich als Dienstanbieter jedoch nicht verpflichtet, übermittelte oder gespeicherte fremde Informationen zu überwachen oder nach Umständen zu forschen, die auf eine rechtswidrige Tätigkeit hinweisen.',
  '### Urheberrecht',
  'Die durch den Seitenbetreiber erstellten Inhalte und Werke auf diesen Seiten unterliegen dem schweizerischen Urheberrecht. Die Vervielfältigung, Bearbeitung, Verbreitung und jede Art der Verwertung ausserhalb der Grenzen des Urheberrechtes bedürfen der schriftlichen Zustimmung des jeweiligen Autors bzw. Erstellers. Downloads und Kopien dieser Seite sind nur für den privaten, nicht kommerziellen Gebrauch gestattet.',
]

export const AGB_LINES: string[] = [
  '## Allgemeine Geschäftsbedingungen',
  'Stand: Mai 2025',
  '### AGB',
  'Diese Allgemeinen Geschäftsbedingungen (AGB) finden auf alle durch Burgmeijer RAI-Experte angebotenen Dienstleistungen Anwendung. Mit der Nutzung der Dienstleistungen von Burgmeijer RAI-Experte akzeptieren Sie die nachfolgenden Bedingungen unverändert und vollumfänglich.',
  '### Allgemeines',
  'Die allgemeinen Geschäftsbedingungen sind Grundlage für eine partnerschaftliche Kundenbeziehung. Wir bemühen uns, Sie zur vollsten Zufriedenheit zu bedienen.',
  '### Geltungsbereich',
  'Burgmeijer RAI-Experte erbringt Dienstleistungen für ihre Kunden nach Massgabe des individuell abgeschlossenen Vertrages, sowie der vorliegenden Geschäftsbedingungen. Abweichende Vereinbarungen erfordern Schriftlichkeit.',
  '### Vertragsabschluss',
  'Burgmeijer RAI-Experte unterbreitet dem Kunden auf Grundlage dessen Wünschen eine persönliche Offerte. Nach Prüfung der Offerte und Erarbeitung allfälliger Änderung stellt Burgmeijer RAI-Experte dem Kunden eine schriftliche Auftragsbestätigung zu. Der Vertrag kommt mit Unterzeichnung dieser Bestätigung zustande.',
  '### Leistungen / Treuepflicht',
  'Burgmeijer RAI-Experte verpflichtet sich, bei der Ausführung des Vertrages in sorgfältiger Weise vorzugehen.',
  '### Geistiges Eigentum',
  'Die Urheber- und alle anderen Rechte an Inhalten, gehören ausschliesslich Burgmeijer RAI-Experte oder den speziell genannten Rechtsinhabern insbesondere das Urheberrecht an allen im Rahmen der Zusammenarbeit mit Burgmeijer RAI-Experte geschaffenen Leistungen. Für die Reproduktion jeglicher Elemente ist die schriftliche Zustimmung bei Burgmeijer RAI-Experte im Voraus einzuholen.',
  '### Zahlungsbedingungen',
  'Rechnungen sind, sofern schriftlich nichts anderes vereinbart, innerhalb von 10 Tagen zu bezahlen. Die Geltendmachung von allfälligen Ansprüchen gegenüber Burgmeijer RAI-Experte berechtigt den Vertragspartner nicht zum Rückbehalt von Zahlungen. Eine Verrechnung mit allfälligen Forderungen gegenüber Burgmeijer RAI-Experte ist ausgeschlossen.',
  '### Annullation',
  'Bei einer Annullation durch den Kunden weniger als 4 Wochen vor Termin werden 50 % der Kosten verrechnet. Bei einer Annullation weniger als 2 Wochen vor Termin, werden 100 % der Kosten verrechnet. Burgmeijer RAI-Experte ist berechtigt, bei unerwarteten Ereignissen einen Termin zu verschieben oder abzusagen. Eine Absage von Burgmeijer RAI-Experte hat keine Kostenfolge für den Kunden.',
  "### Änderungen der AGB's",
  "Diese AGB's können jederzeit und ohne Vorankündigung geändert werden.",
  '### Gerichtsstand',
  'Unsere Geschäftstätigkeit basiert ausschliesslich auf schweizerischem Recht. Der Gerichtsstand ist Zürich.',
]

export const DATENSCHUTZ_LINES: string[] = [
  '## Datenschutzerklärung',
  'Stand: Mai 2025',
  '### 1. Einleitung',
  'Der Schutz Ihrer persönlichen Daten ist uns wichtig. Gestützt auf Artikel 13 der Schweizerischen Bundesverfassung und die datenschutzrechtlichen Bestimmungen des Bundes (Datenschutzgesetz, DSG) hat jede Person Anspruch auf Schutz ihrer Privatsphäre sowie auf Schutz vor Missbrauch ihrer persönlichen Daten.',
  'Wir, BURGMEIJER RAI-Experte, behandeln Ihre personenbezogenen Daten vertraulich und entsprechend der gesetzlichen Datenschutzvorschriften sowie dieser Datenschutzerklärung. Diese Datenschutzerklärung informiert Sie darüber, wie und zu welchem Zweck wir personenbezogene Daten erheben, verarbeiten und nutzen, wenn Sie unsere Website besuchen oder unsere Dienstleistungen in Anspruch nehmen.',
  '### 2. Verantwortliche Stelle und Kontaktdaten',
  'Verantwortlich für die Datenverarbeitung auf dieser Website ist:',
  'Marco Burgmeijer, RAI-Experte, Sunnmatt 1, 8634 Hombrechtikon, Schweiz',
  'Telefon: +41 76 457 44 82 · E-Mail: rai-experte@gmx.ch · Website: www.rai-experte.ch · UID: CHE-294.549.553',
  '### 3. Erhebung und Verarbeitung personenbezogener Daten',
  'Wir erheben und verarbeiten personenbezogene Daten nur, soweit dies für die Bereitstellung einer funktionsfähigen Website sowie unserer Inhalte und Leistungen erforderlich ist. Die Erhebung und Verarbeitung personenbezogener Daten unserer Nutzer erfolgt grundsätzlich nur nach Einwilligung des Nutzers oder in solchen Fällen, in denen eine vorherige Einholung einer Einwilligung aus tatsächlichen Gründen nicht möglich ist und die Verarbeitung der Daten durch gesetzliche Vorschriften gestattet ist.',
  '### 3.1 Besuch unserer Website und Server-Logfiles',
  'Bei jedem Besuch unserer Website erfasst unser System automatisiert Daten und Informationen vom Computersystem des aufrufenden Rechners. Folgende Daten werden hierbei erhoben:',
  '- Informationen über den Browsertyp und die verwendete Version',
  '- Das Betriebssystem des Nutzers',
  '- Den Internet-Service-Provider des Nutzers',
  '- Die IP-Adresse des Nutzers',
  '- Datum und Uhrzeit des Zugriffs',
  '- Websites, von denen das System des Nutzers auf unsere Website gelangt',
  '- Websites, die vom System des Nutzers über unsere Website aufgerufen werden',
  'Diese Daten werden in den Logfiles unseres Systems gespeichert. Eine Speicherung dieser Daten zusammen mit anderen personenbezogenen Daten des Nutzers findet nicht statt. Die vorübergehende Speicherung der IP-Adresse durch das System ist notwendig, um eine Auslieferung der Website an den Rechner des Nutzers zu ermöglichen. Hierfür muss die IP-Adresse des Nutzers für die Dauer der Sitzung gespeichert bleiben.',
  '### 3.2 Kontaktformular',
  'Wenn Sie uns per Kontaktformular Anfragen zukommen lassen, werden Ihre Angaben aus dem Anfrageformular inklusive der von Ihnen dort angegebenen Kontaktdaten zwecks Bearbeitung der Anfrage und für den Fall von Anschlussfragen bei uns gespeichert. Diese Daten geben wir nicht ohne Ihre Einwilligung weiter.',
  'Die Verarbeitung der in das Kontaktformular eingegebenen Daten erfolgt somit ausschliesslich auf Grundlage Ihrer Einwilligung. Sie können diese Einwilligung jederzeit widerrufen. Dazu reicht eine formlose Mitteilung per E-Mail an uns. Die Rechtmässigkeit der bis zum Widerruf erfolgten Datenverarbeitungsvorgänge bleibt vom Widerruf unberührt.',
  'Die von Ihnen im Kontaktformular eingegebenen Daten verbleiben bei uns, bis Sie uns zur Löschung auffordern, Ihre Einwilligung zur Speicherung widerrufen oder der Zweck für die Datenspeicherung entfällt (z.B. nach abgeschlossener Bearbeitung Ihrer Anfrage).',
  '### 3.3 Daten im Rahmen unserer Dienstleistungen',
  'Im Rahmen unserer Dienstleistungen erheben und verarbeiten wir personenbezogene Daten zur Durchführung vorvertraglicher Massnahmen und zur Erfüllung unserer vertraglichen Verpflichtungen. Die hierbei erhobenen Daten umfassen in der Regel:',
  '- Name und Kontaktdaten (Adresse, Telefonnummer, E-Mail-Adresse)',
  '- Daten zur Rechnungsstellung und zum Zahlungsverkehr',
  '- Korrespondenz mit Ihnen',
  '- Informationen, die für die Erbringung unserer Dienstleistungen erforderlich sind',
  '### 4. Zwecke der Datenverarbeitung',
  'Wir verarbeiten Ihre personenbezogenen Daten für folgende Zwecke:',
  '- Zur Gewährleistung eines reibungslosen Verbindungsaufbaus der Website',
  '- Zur Gewährleistung einer komfortablen Nutzung unserer Website',
  '- Zur Auswertung der Systemsicherheit und -stabilität',
  '- Zur Kontaktaufnahme und Kommunikation mit Ihnen',
  '- Zur Beantwortung von Anfragen',
  '- Zur Erbringung unserer Dienstleistungen',
  '- Zur Abwicklung von Verträgen',
  '- Zu administrativen Zwecken',
  '### 5. Rechtsgrundlagen der Datenverarbeitung',
  'Die Rechtsgrundlage für die Verarbeitung von personenbezogenen Daten in der Schweiz ist das Bundesgesetz über den Datenschutz (DSG). Soweit wir für Verarbeitungsvorgänge personenbezogener Daten eine Einwilligung der betroffenen Person einholen, dient diese als Rechtsgrundlage. Bei der Verarbeitung von personenbezogenen Daten, die zur Erfüllung eines Vertrages, dessen Vertragspartei die betroffene Person ist, erforderlich ist, dient der Vertrag als Rechtsgrundlage. Gleiches gilt für Verarbeitungsvorgänge, die zur Durchführung vorvertraglicher Massnahmen erforderlich sind.',
  '### 6. Datenweitergabe und Datenübermittlung',
  'Eine Übermittlung Ihrer persönlichen Daten an Dritte zu anderen als den im Folgenden aufgeführten Zwecken findet nicht statt. Wir geben Ihre persönlichen Daten nur an Dritte weiter, wenn:',
  '- Sie Ihre ausdrückliche Einwilligung dazu erteilt haben',
  '- Die Weitergabe zur Durchführung unserer Dienstleistungen oder zur Erfüllung vertraglicher Verpflichtungen erforderlich ist',
  '- Die Weitergabe zur Erfüllung einer rechtlichen Verpflichtung erforderlich ist',
  '- Die Weitergabe zur Geltendmachung, Ausübung oder Verteidigung von Rechtsansprüchen erforderlich ist',
  'In manchen Fällen setzen wir für die Verarbeitung Ihrer Daten Dienstleister ein, die uns bei der Datenverarbeitung unterstützen und streng an unsere Weisungen gebunden sind. Mit diesen Dienstleistern haben wir entsprechende Verträge zur Auftragsverarbeitung abgeschlossen.',
  '### 7. Dauer der Datenspeicherung',
  'Die personenbezogenen Daten der betroffenen Person werden gelöscht oder gesperrt, sobald der Zweck der Speicherung entfällt. Eine Speicherung kann darüber hinaus erfolgen, wenn dies durch gesetzliche Vorgaben, denen wir unterliegen, vorgesehen wurde. Eine Sperrung oder Löschung der Daten erfolgt auch dann, wenn eine durch die genannten Vorschriften vorgeschriebene Speicherfrist abläuft, es sei denn, dass eine Erforderlichkeit zur weiteren Speicherung der Daten für einen Vertragsabschluss oder eine Vertragserfüllung besteht.',
  '### 8. Ihre Rechte',
  'Sie haben folgende Rechte gegenüber uns hinsichtlich der Sie betreffenden personenbezogenen Daten:',
  '- Recht auf Auskunft über die zu Ihrer Person gespeicherten Daten',
  '- Recht auf Berichtigung oder Löschung',
  '- Recht auf Einschränkung der Verarbeitung',
  '- Recht auf Widerspruch gegen die Verarbeitung',
  '- Recht auf Datenübertragbarkeit',
  '- Recht, Ihre einmal erteilte Einwilligung jederzeit gegenüber uns zu widerrufen',
  '- Recht auf Beschwerde bei einer Aufsichtsbehörde',
  'Wenn Sie eines dieser Rechte wahrnehmen möchten, wenden Sie sich bitte an die oben genannten Kontaktdaten.',
  'Sollten Sie der Ansicht sein, dass die Verarbeitung Ihrer personenbezogenen Daten gegen geltendes Datenschutzrecht verstösst, können Sie bei der zuständigen Aufsichtsbehörde Beschwerde einlegen. In der Schweiz ist dies der Eidgenössische Datenschutz- und Öffentlichkeitsbeauftragte (EDÖB): www.edoeb.admin.ch.',
  '### 9. Datensicherheit',
  'Wir treffen angemessene technische und organisatorische Massnahmen, um Ihre personenbezogenen Daten gegen zufällige oder vorsätzliche Manipulationen, teilweisen oder vollständigen Verlust, Zerstörung oder gegen den unbefugten Zugriff Dritter zu schützen. Unsere Sicherheitsmassnahmen werden entsprechend der technologischen Entwicklung fortlaufend verbessert.',
  'Die Datenübertragung im Internet (z.B. bei der Kommunikation per E-Mail) kann jedoch Sicherheitslücken aufweisen. Ein lückenloser Schutz der Daten vor dem Zugriff durch Dritte ist nicht möglich.',
  '### 10. Aktualität und Änderung dieser Datenschutzerklärung',
  'Diese Datenschutzerklärung ist aktuell gültig und hat den Stand Mai 2025.',
  'Wir behalten uns vor, diese Datenschutzerklärung jederzeit zu ändern, um sie an geänderte Rechtslagen oder bei Änderungen des Dienstes sowie der Datenverarbeitung anzupassen. Die neue Datenschutzerklärung gilt dann für alle Ihre künftigen Besuche unserer Website. Sofern eine Einwilligung erforderlich ist oder Bestandteile der Datenschutzerklärung Regelungen des Vertragsverhältnisses mit unseren Kunden enthalten, werden wir die Änderungen nur mit Ihrer Zustimmung vornehmen.',
  'Wir empfehlen Ihnen, diese Datenschutzerklärung regelmässig zu konsultieren, um über den Schutz der von uns erfassten personenbezogenen Daten informiert zu bleiben.',
]
