/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    angebote: Angebote;
    referenzen: Referenzen;
    veranstaltungen: Veranstaltungen;
    anmeldungen: Anmeldungen;
    kontaktanfragen: Kontaktanfragen;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {
    veranstaltungen: {
      anmeldungen: 'anmeldungen';
    };
  };
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    angebote: AngeboteSelect<false> | AngeboteSelect<true>;
    referenzen: ReferenzenSelect<false> | ReferenzenSelect<true>;
    veranstaltungen: VeranstaltungenSelect<false> | VeranstaltungenSelect<true>;
    anmeldungen: AnmeldungenSelect<false> | AnmeldungenSelect<true>;
    kontaktanfragen: KontaktanfragenSelect<false> | KontaktanfragenSelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    preise: Preise;
    kontakt: Kontakt;
    rechtstexte: Rechtstexte;
    ueberMich: UeberMich;
    seoDefaults: SeoDefault;
  };
  globalsSelect: {
    preise: PreiseSelect<false> | PreiseSelect<true>;
    kontakt: KontaktSelect<false> | KontaktSelect<true>;
    rechtstexte: RechtstexteSelect<false> | RechtstexteSelect<true>;
    ueberMich: UeberMichSelect<false> | UeberMichSelect<true>;
    seoDefaults: SeoDefaultsSelect<false> | SeoDefaultsSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * Wer kann sich im RAI-Experte-Admin anmelden?
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  name?: string | null;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * Bilder und Logos. Alt-Text ist Pflicht: kurze, konkrete Beschreibung.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  /**
   * Was ist auf dem Bild zu sehen? 1 Satz, konkret. Pflicht für Screenreader und SEO.
   */
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumb?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    hero?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * Die 4 Angebote. Reihenfolge über das Feld „Nummer".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angebote".
 */
export interface Angebote {
  id: number;
  /**
   * Reihenfolge (1–4).
   */
  nummer: number;
  titel: string;
  /**
   * Muss exakt bleiben: tarifstufen | heiminterne | beratung | wechselbesarai
   */
  slug: string;
  /**
   * Farbe der Kachel (je Angebot eine Farbe).
   */
  kachelFarbe: 'offer-1' | 'offer-2' | 'offer-3' | 'offer-4';
  /**
   * Filter-Zuordnung auf der Startseite.
   */
  filterGruppe: 'coaching' | 'beratung' | 'wechsel';
  /**
   * Kurzer Kachel-Text auf der Startseite (kann mit Zeilenumbrüchen).
   */
  kurztext: string;
  /**
   * Seiteninhalt unter der Überschrift „Beschreibung".
   */
  beschreibung: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  /**
   * Suchmaschinen-Snippet und Social-Sharing-Karte. Wenn leer, wird der Seiten-Titel als Fallback verwendet.
   */
  seo?: {
    /**
     * Empfohlen max. 60–70 Zeichen — Google schneidet länger ab.
     */
    title?: string | null;
    /**
     * Empfohlen max. 160 Zeichen, aktiv und knackig formuliert.
     */
    description?: string | null;
    /**
     * Optional. Empfohlen: 1200×630. Fallback ist das Marco-Foto.
     */
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Kundenstimmen / Referenzen. Reihenfolge über „Reihenfolge".
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referenzen".
 */
export interface Referenzen {
  id: number;
  /**
   * Position im Carousel.
   */
  reihenfolge: number;
  /**
   * Name der Institution.
   */
  einrichtung: string;
  /**
   * Externe Website der Einrichtung (öffnet in neuem Tab). Optional.
   */
  websiteUrl?: string | null;
  /**
   * Logo / Bild der Einrichtung.
   */
  logo?: (number | null) | Media;
  /**
   * Testimonial-Text. Darf leer sein (z. B. nur Projekt-Info).
   */
  zitat?: string | null;
  /**
   * Name der zitierten Person.
   */
  autorName?: string | null;
  /**
   * Funktion / Rolle der Person.
   */
  autorFunktion?: string | null;
  /**
   * Zeitraum / Go-Life / Art des Projekts.
   */
  projektInfo?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Schulungen & Veranstaltungen. Status „offen" erscheint auf der Startseite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "veranstaltungen".
 */
export interface Veranstaltungen {
  id: number;
  titel: string;
  /**
   * URL-Fragment, klein und mit Bindestrichen — z. B. "tarifstufen". Wird Teil der öffentlichen URL.
   */
  slug: string;
  /**
   * Kurze Einleitung / Beschreibung der Veranstaltung (erscheint oben im Detail).
   */
  beschreibung?: string | null;
  /**
   * Start (Datum + Uhrzeit).
   */
  datumVon: string;
  /**
   * Ende (Datum + Uhrzeit). Optional.
   */
  datumBis?: string | null;
  /**
   * z. B. „Stiftung Loogarten, Esslingen".
   */
  ort: string;
  /**
   * Optionaler Google-Maps-Link zum Ort (Ort wird dann anklickbar).
   */
  ortMapsUrl?: string | null;
  /**
   * Optionales Bild.
   */
  bild?: (number | null) | Media;
  /**
   * z. B. „Pflegehelferinnen und Pflegehelfer".
   */
  zielgruppe?: string | null;
  /**
   * Lernziele der Schulung (Aufzählung).
   */
  ziele?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Programm / Themenbereiche (mit Zwischenüberschriften und Listen).
   */
  themen?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * CHF. 0 = kostenlos.
   */
  preis?: number | null;
  /**
   * z. B. „Halbtages-Schulung CHF 95, Zahlung auf Rechnung".
   */
  preisInfo?: string | null;
  /**
   * Maximale Teilnehmerzahl.
   */
  plaetze: number;
  /**
   * Optional.
   */
  anmeldeschluss?: string | null;
  status: 'offen' | 'ausgebucht' | 'abgesagt' | 'vergangen';
  /**
   * Wer sich für diese Veranstaltung angemeldet hat.
   */
  anmeldungen?: {
    docs?: (number | Anmeldungen)[];
    hasNextPage?: boolean;
    totalDocs?: number;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingegangene Event-Anmeldungen.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anmeldungen".
 */
export interface Anmeldungen {
  id: number;
  veranstaltung: number | Veranstaltungen;
  vorname: string;
  nachname: string;
  email: string;
  telefon?: string | null;
  /**
   * Optional, z. B. Pflegezentrum.
   */
  firma?: string | null;
  anzahlPersonen?: number | null;
  bemerkung?: string | null;
  /**
   * Beim Anmelden bestätigt.
   */
  agbAkzeptiert?: boolean | null;
  status?: ('neu' | 'bestätigt' | 'storniert') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * Eingegangene Kontaktanfragen aus dem Formular.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontaktanfragen".
 */
export interface Kontaktanfragen {
  id: number;
  name: string;
  email: string;
  telefon?: string | null;
  nachricht: string;
  /**
   * Angebot/Seite, von der die Anfrage kam (leer = Startseite).
   */
  herkunft?: string | null;
  status?: ('neu' | 'erledigt') | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'angebote';
        value: number | Angebote;
      } | null)
    | ({
        relationTo: 'referenzen';
        value: number | Referenzen;
      } | null)
    | ({
        relationTo: 'veranstaltungen';
        value: number | Veranstaltungen;
      } | null)
    | ({
        relationTo: 'anmeldungen';
        value: number | Anmeldungen;
      } | null)
    | ({
        relationTo: 'kontaktanfragen';
        value: number | Kontaktanfragen;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  name?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumb?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        hero?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "angebote_select".
 */
export interface AngeboteSelect<T extends boolean = true> {
  nummer?: T;
  titel?: T;
  slug?: T;
  kachelFarbe?: T;
  filterGruppe?: T;
  kurztext?: T;
  beschreibung?: T;
  seo?:
    | T
    | {
        title?: T;
        description?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "referenzen_select".
 */
export interface ReferenzenSelect<T extends boolean = true> {
  reihenfolge?: T;
  einrichtung?: T;
  websiteUrl?: T;
  logo?: T;
  zitat?: T;
  autorName?: T;
  autorFunktion?: T;
  projektInfo?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "veranstaltungen_select".
 */
export interface VeranstaltungenSelect<T extends boolean = true> {
  titel?: T;
  slug?: T;
  beschreibung?: T;
  datumVon?: T;
  datumBis?: T;
  ort?: T;
  ortMapsUrl?: T;
  bild?: T;
  zielgruppe?: T;
  ziele?:
    | T
    | {
        text?: T;
        id?: T;
      };
  themen?: T;
  preis?: T;
  preisInfo?: T;
  plaetze?: T;
  anmeldeschluss?: T;
  status?: T;
  anmeldungen?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "anmeldungen_select".
 */
export interface AnmeldungenSelect<T extends boolean = true> {
  veranstaltung?: T;
  vorname?: T;
  nachname?: T;
  email?: T;
  telefon?: T;
  firma?: T;
  anzahlPersonen?: T;
  bemerkung?: T;
  agbAkzeptiert?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontaktanfragen_select".
 */
export interface KontaktanfragenSelect<T extends boolean = true> {
  name?: T;
  email?: T;
  telefon?: T;
  nachricht?: T;
  herkunft?: T;
  status?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * Tarif-Tabelle. Wird auf Startseite und allen Angebots-Seiten angezeigt.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preise".
 */
export interface Preise {
  id: number;
  /**
   * Jede Zeile: Titel (links) + Beschreibung (rechts).
   */
  zeilen?:
    | {
        titel: string;
        /**
         * Mehrzeilig erlaubt (Zeilenumbrüche werden angezeigt).
         */
        beschreibung: string;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Adresse, E-Mail, Telefon, UID, LinkedIn — überall identisch verwendet.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt".
 */
export interface Kontakt {
  id: number;
  strasse: string;
  plzOrt: string;
  land?: string | null;
  email: string;
  telefon: string;
  uid?: string | null;
  linkedin?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Impressum, AGB und Datenschutzerklärung — voll editierbar.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rechtstexte".
 */
export interface Rechtstexte {
  id: number;
  impressum?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  agb?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  datenschutz?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Intro-Text, Über-mich-Text und Marco-Bilder der Startseite.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ueberMich".
 */
export interface UeberMich {
  id: number;
  /**
   * Überschrift der Intro-Sektion. Zeilenumbrüche werden übernommen.
   */
  introHeading?: string | null;
  introAbsaetze?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Rundes Foto rechts neben dem Intro-Text.
   */
  rundfoto?: (number | null) | Media;
  name?: string | null;
  spalte1?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  spalte2?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * 3 Fotos (Hund / Computer / Garten).
   */
  galerie?:
    | {
        bild: number | Media;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * Marken-/Hero-Texte, Standard-OG-Bild und Site-weite SEO-Defaults.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoDefaults".
 */
export interface SeoDefault {
  id: number;
  /**
   * Marken-Titel (Header, Hero, Footer). Erstes Wort wird fett dargestellt.
   */
  siteTitle?: string | null;
  /**
   * og:site_name.
   */
  siteName?: string | null;
  /**
   * Untertitel im Hero (h3).
   */
  heroSubtitel?: string | null;
  /**
   * Fallback-Meta-Description für die Startseite.
   */
  defaultMetaDescription?: string | null;
  /**
   * Standard-Social-Sharing-Bild (Fallback, 1200×630).
   */
  defaultOgImage?: (number | null) | Media;
  /**
   * Inhalt des google-site-verification Meta-Tags.
   */
  googleSiteVerification?: string | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "preise_select".
 */
export interface PreiseSelect<T extends boolean = true> {
  zeilen?:
    | T
    | {
        titel?: T;
        beschreibung?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "kontakt_select".
 */
export interface KontaktSelect<T extends boolean = true> {
  strasse?: T;
  plzOrt?: T;
  land?: T;
  email?: T;
  telefon?: T;
  uid?: T;
  linkedin?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "rechtstexte_select".
 */
export interface RechtstexteSelect<T extends boolean = true> {
  impressum?: T;
  agb?: T;
  datenschutz?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "ueberMich_select".
 */
export interface UeberMichSelect<T extends boolean = true> {
  introHeading?: T;
  introAbsaetze?:
    | T
    | {
        text?: T;
        id?: T;
      };
  rundfoto?: T;
  name?: T;
  spalte1?:
    | T
    | {
        text?: T;
        id?: T;
      };
  spalte2?:
    | T
    | {
        text?: T;
        id?: T;
      };
  galerie?:
    | T
    | {
        bild?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "seoDefaults_select".
 */
export interface SeoDefaultsSelect<T extends boolean = true> {
  siteTitle?: T;
  siteName?: T;
  heroSubtitel?: T;
  defaultMetaDescription?: T;
  defaultOgImage?: T;
  googleSiteVerification?: T;
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}